### ISSUE TITLE
Add a map page

### ISSUE THREAD

**Issue by rbento1096** [uatisdeproblem/egm-app#61]
> As a user, I'd like to see a map on the app so that I can see where the venues are located, set custom waypoints and check local suggested places by the OC

- [x] Add the app stack as seen on the previous version of the app (react)
- [ ] Allow the user to add his own points of interest (more than 1)
- [ ] Allow the organization to add the venus as well as other points of interest (such as pubs, gardens,pharmacies, etc...)

**Comment by uatisdeproblem** [comment]
Ok, I'll do it before the next weekend.

**Comment by uatisdeproblem** [comment]
Useful ref: https://docs.aws.amazon.com/location/latest/developerguide/dev-location-libraries.html#loc-sdk-auth

**Comment by uatisdeproblem** [comment]
Link to old source code: https://github.com/uatisdeproblem/egm-app/blob/81df12459e17ef85f75c6b9ca93c24454dcd1117/front-end/src/components/MapBox.tsx#L123
