### ISSUE TITLE
Feat: registrations export data

### ISSUE THREAD

**Issue by rbento1096** [uatisdeproblem/egm-app#79]
As a user with permissions to view the user list (DL, OC, Admin...) I want to be able to export the users' registration data to a csv/excel file

**Comment by uatisdeproblem** [comment]
Suggestion: instead of downloading the registration of each user one by one, wouldn't it be better to have a download button in the list and download alltogether every user that the current user's permissions allow? (e.g. admin → all users, DL → country users)? @rbento1096

**Comment by rbento1096** [comment]
ah yes, sorry, I meant 'users' registration data', i'll fix it now.

**Comment by uatisdeproblem** [comment]
To allow maximum flexibility, we download only the users in the current search (i.e. the list after the filters are applied). You can fire the download with the green download icon after the searchbar.

<img width="1609" alt="Screenshot 2023-11-25 at 14 46 33" src="https://github.com/uatisdeproblem/egm-app/assets/3777036/be01a1c0-6253-4e53-a2b4-506b95ac0682">

[I attach an example of the Excel generated in the development environment](https://github.com/uatisdeproblem/egm-app/files/13464250/Users.xlsx); feel free to change the name of the fields or any other customisation that the team may require.
