### ISSUE TITLE
Feat: vote erasmus destination of the year

### ISSUE THREAD

**Issue by rbento1096** [uatisdeproblem/egm-app#81]
As a user I'd like to be able to vote for this year's Erasmus Destination of the Year
As an admin/CT I'd like to be able to insert this year's candidate destinations through a dedicated UI.
Users should also be blocked from voting on own country
Vote must be anonymous

**Comment by uatisdeproblem** [comment]
> Users should also be blocked from voting on own country

1. Can any kind of user vote? Or only registered ones, only ESNers, etc.?
2. If any user can vote, a user without a Country can vote for anything, right?

> Vote must be anonymous

3. This means that once the vote is cast, you can't change it anymore, and you can't even see what you voted for yourself. Is that cool?

@rbento1096

**Comment by uatisdeproblem** [comment]
I'll keep the internal name generic to "contest" (instead of Erasmus of the Year), to be more flexible for possible changes in the next editions.

**Comment by rbento1096** [comment]
> Can any kind of user vote? Or only registered ones, only ESNers, etc.?

Only registered ESNers

> This means that once the vote is cast, you can't change it anymore, and you can't even see what you voted for yourself. Is that cool?

Yes, exactly! :)

**Comment by uatisdeproblem** [comment]
You can test the new feature on the dev environment.

As anticipated, I created a more general structure to allow multiple contests — not only the Destination of the Year. This way, we can enhance user engagement on the app via silly/informal/formal contests throughout the event.
