### ISSUE TITLE
[BUG]: users with unknown country/section

### ISSUE THREAD

**Issue by rbento1096** [uatisdeproblem/egm-app#82]
Some users coming from galaxy have their country/section marked as 'Unknown'.

After talking with Darwyn and Adel, this problem comes users registering to Galaxy without having an associated role/section on the platform.

This isn't a serious problem as these users can't do anything on the app, but should be blocked. I am still waiting from feedback from them as some legit users also show up with no role. As soon as we know it is fixed, we will block users with no role

**Comment by rbento1096** [comment]
we will no longer sync with ESNaccounts after every login. Sections and countries that are incorrect will be changed directly on DynamoDB until we are sure that ESnaccounts has updated and correct data

**Comment by uatisdeproblem** [comment]
Is this closed? @rbento1096
